#!/usr/bin/env bash
source "${HOME}/.dotfiles/.dotfiles_includes"

##
# Install elasticsearch and kibana.
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#
name="elasticsearch"
version="2.4.4"
yum_enablerepo=""

if [[ -n "$1" ]]; then
	version="$1"
fi

source_url=""
source_directory=""

if ! command_exists ${name}; then
	echo -e "${RESET}${BBLUE}Installing ${name} ${GREEN}${version}${RESET}"

	yum -y install \
	java \
	https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/rpm/elasticsearch/${version}/elasticsearch-${version}.rpm \
	https://download.elastic.co/kibana/kibana/kibana-4.6.4-x86_64.rpm

	# Create snapshot directory.
	mkdir -pv /home/elasticsearch/snapshots
	chown -R elasticsearch:elasticsearch /home/elasticsearch
	chmod -R 770 /home/elasticsearch
	chmod -R +X /home/elasticsearch

	echo "script.inline: on" >> /etc/elasticsearch/elasticsearch.yml
	echo "script.indexed: on" >> /etc/elasticsearch/elasticsearch.yml
	echo "network.host: 0.0.0.0" >> /etc/elasticsearch/elasticsearch.yml
	echo "path.repo: /vagrant/snapshots" >> /etc/elasticsearch/elasticsearch.yml

	/usr/share/elasticsearch/bin/plugin install analysis-phonetic
	/usr/share/elasticsearch/bin/plugin install analysis-icu

	/opt/kibana/bin/kibana plugin --install elastic/sense

	#chkconfig elasticsearch on
	#/etc/init.d/elasticsearch restart
	#chkconfig kibana on
	#service kibana start

	echo -e "${GREEN}${name} installed.${RESET}"
fi
