#!/usr/bin/env bash
source "${HOME}/.dotfiles/.dotfiles_includes"

##
# Install Percona's MySQL version and extensions.
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#
name="mysql"
version=""
if [[ -n "$1" ]]; then
	version="$1"
fi
source_url=""
source_directory=""

if ! command_exists ${name}; then
	echo -e "${RESET}${BBLUE}Installing ${name} ${GREEN}${version}${RESET}"

	yum -y install \
	http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm \
	Percona-Server-client-56 \
	Percona-Server-server-56 \
	percona-toolkit \
	percona-xtrabackup \
	mysql-utilities \
	mysqlreport \
	mysqltuner

	echo -e "${GREEN}${name} installed.${RESET}"
fi
