#!/usr/bin/env bash
source "${HOME}/.dotfiles/.dotfiles_includes"

##
# Install Percona's MySQL version and extensions.
#
# Notes:
# - If you get PID/sock issues, ensure permissions are set.
# - If mysqld won't start, check the standard mysql log files, and check
# /var/log/messages log for mysql issues, like running out of memory (ensure
# the box has enough), or SELinux not permitting actions (like preventing
# access to ~/.my.cnf).
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#
name="mysql"
version=""
if [[ -n "$1" ]]; then
	version="$1"
fi
source_url=""
source_directory=""

if ! command_exists ${name}; then
	echo -e "${RESET}${BBLUE}Installing ${name} ${GREEN}${version}${RESET}"

	yum -y install \
	http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm \
	Percona-Server-client-56 \
	Percona-Server-server-56 \
	Percona-Server-devel-56 \
	percona-toolkit \
	percona-xtrabackup \
	mysql-utilities \
	mysqlreport \
	mysqltuner

	mkdir -pv /var/lib/mysql && chown -R mysql:mysql /var/lib/mysql && chmod -R 755 /var/lib/mysql
	mkdir -pv /var/log/mysql && chown -R mysql:mysql /var/log/mysql && chmod -R 755 /var/log/mysql
	mkdir -pv /home/mysql && chown -R mysql:mysql /home/mysql && chmod -R 770 /home/mysql
	#mysql_install_db
	#/etc/init.d/mysql restart
	#mysql_secure_installation
	/etc/init.d/mysql stop
	chkconfig mysql off

	echo -e "${GREEN}${name} installed.${RESET}"
fi
