#!/usr/bin/env bash
source "${DOTFILES_BOOTSTRAP_FILE}"

##
# Install nginx version from ius.
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#
name="nginx"
version="nginx"
if [[ -n "$1" ]]; then
	version="$1"
fi
source_url=""
source_directory=""

if ! command_exists ${name}; then
	echo -e "${RESET}${BBLUE}Installing ${name} ${GREEN}${version}${RESET}"

	yum -y install \
	http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm \
	${version}

	/etc/init.d/nginx restart
	chkconfig nginx on

	echo -e "${GREEN}${name} installed.${RESET}"
fi
