#!/usr/bin/env bash
source "${HOME}/.dotfiles/.dotfiles_includes"

##
# Install specific PHP version and extensions.
#
# CentOS carries a very old version, so replace it with the one defined in the
# ius repo.
#
# By default, this will only run if PHP is not already installed. This is to
# ensure that existing systems do not accidentally have their versions changed.
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#
name="php"
version="php71u"
yum_enablerepo=""

if [[ -n "$1" ]]; then
	version="$1"
fi

if [[ "${version}" == "php55u" ]]; then
	yum_enablerepo="--enablerepo=ius-archive"
fi

source_url=""
source_directory=""

if ! command_exists ${name}; then
	echo -e "${RESET}${BBLUE}Installing ${name} ${GREEN}${version}${RESET}"

	yum -y install \
	https://centos6.iuscommunity.org/ius-release.rpm \
	${yum_enablerepo} \
	${version} \
	${version}-cli \
	${version}-common \
	${version}-devel \
	${version}-fpm \
	${version}-fpm-nginx \
	${version}-gd \
	${version}-imap \
	${version}-intl \
	${version}-ioncube-loader \
	${version}-json \
	${version}-mbstring \
	${version}-mcrypt \
	${version}-mhash \
	${version}-mysqlnd \
	${version}-opcache \
	${version}-pear \
	${version}-pecl-geoip \
	${version}-pecl-jsonc \
	${version}-pecl-memcached \
	${version}-pecl-redis \
	${version}-pecl-xdebug \
	${version}-pdo \
	${version}-pdo_mysql \
	${version}-process \
	${version}-soap \
	${version}-xml

	echo -e "${GREEN}${name} installed.${RESET}"
fi

## TODO
# This is for remi-safe, enabled by default. All others are disabled by default.
# Remi-safe is used in vagrantshell only for php56. This repo allows a parallel
# installation of PHP in another version.
#yum -y install http://rpms.remirepo.net/enterprise/remi-release-6.rpm
#Install remi-safe version of PHP 5.6.
#PHP_VERSION_REMI_SAFE="php56-php"
#$PHP_VERSION_REMI_SAFE-ioncube-loader
# These conflict with IUS.
# $PHP_VERSION_REMI_SAFE-pecl-memcached
# $PHP_VERSION_REMI_SAFE-pecl-memcached-debuginfo
