#!/usr/bin/env bash
source "${HOME}/.dotfiles/.dotfiles_includes"

##
# Install specific PHP version and extensions.
#
# CentOS carries a very old version, so replace it with the one defined in the
# ius repo.
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#
name="php"
version="php56u"
if [[ -n "$1" ]]; then
	version="$1"
fi
source_url=""
source_directory=""

if ! command_exists ${name}; then
	echo -e "${RESET}${BBLUE}Installing ${name} ${GREEN}${version}${RESET}"

	yum -y install \
	https://centos6.iuscommunity.org/ius-release.rpm \
	${version} \
	${version}-cli \
	${version}-common \
	${version}-devel \
	${version}-fpm \
	${version}-gd \
	${version}-imap \
	${version}-ioncube-loader \
	${version}-mbstring \
	${version}-mcrypt \
	${version}-mhash \
	${version}-mysqlnd \
	${version}-opcache \
	${version}-pecl-geoip \
	${version}-pecl-jsonc \
	${version}-pecl-memcached \
	${version}-pecl-redis \
	${version}-pecl-xdebug \
	${version}-pdo \
	${version}-process \
	${version}-soap \
	${version}-xml

	# Composer
	if ! command_exists composer; then
		echo -e "${GREEN}Installing composer${RESET}"
		curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin
	fi

	echo -e "${GREEN}${name} installed.${RESET}"
fi
