#!/usr/bin/env bash
source "${DOTFILES_INCLUDES_PATH}"

##
# Install plexdrive.
#
# https://github.com/dweidenfeld/plexdrive
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#
name="plexdrive"
version="5.0.0"
if [[ -n "$1" ]]; then
	version="$1"
fi
source_url="https://github.com/dweidenfeld/plexdrive/releases/download/${version}/plexdrive-linux-amd64"
source_directory=""

echo -e "${RESET}${BBLUE}Installing ${name} ${GREEN}${version}${RESET}"

cd /usr/local/bin/ \
	&& wget ${source_url} \
	&& mv plexdrive-linux-amd64 plexdrive \
	&& chmod +x plexdrive \

mkdir -p /mnt/plexdrive

echo 'SHELL=/bin/bash
PATH=$HOME:$HOME/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
MAILTO="root"
*/1 * * * * root  pgrep plexdrive > /dev/null || plexdrive mount --cache-file=/root/.plexdrive/cache.bolt --fuse-options=allow_other --verbosity=3 /mnt/plexdrive > /var/log/plexdrive.log
' > /etc/cron.d/plexdrive

/etc/init.d/crond restart

echo -e "${GREEN}${name} installed.${RESET}"
