#!/usr/bin/env bash
source "${HOME}/.dotfiles/.dotfiles_includes"

##
# Install Plex Media Server.
#
# This uses a really tool by mrworf from:
# https://github.com/mrworf/plexupdate
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#
name="plexmediaserver"
version="plexmediaserver"
if [[ -n "$1" ]]; then
	version="$1"
fi
source_url=""
source_directory=""

echo -e "${RESET}${BBLUE}Installing ${name} ${GREEN}${version}${RESET}"

bash -c "$(wget -qO - https://raw.githubusercontent.com/mrworf/plexupdate/master/extras/installer.sh)"

echo -e "${GREEN}${name} installed.${RESET}"
