#!/usr/bin/env bash
source "${DOTFILES_INCLUDES_PATH}"

##
# plexbox
#
# This is just the name I give to my local plexbox instance. This script
# consolidates the work of various scripts, each responsible for a service
# on the plexbox instance. It also provides the basic filesystem structure
# that most of these services use.
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#
name="plexbox"
version="plexbox"
if [[ -n "$1" ]]; then
	version="$1"
fi
source_url=""
source_directory=""

echo -e "${RESET}${BBLUE}Installing ${name} ${GREEN}${version}${RESET}"

./deluge_install
./plexdrive_install
./plexmediaserver_install

echo -e "${GREEN}${name} installed.${RESET}"

echo -e "Remember to copy deluge, rclone, plexdrive, and plex metadata configs."
