#!/usr/bin/env bash
source "${HOME}/.dotfiles/.dotfiles_includes"

##
# Download, compile, and install latest version of tmux.
#
# Note that all of the dependencies have been declared in ../yum, along
# with a variety of other utilities that should be installed. This script,
# therefore, assumes that its dependencies are already installed.
#
# This was created and works on CentOS 6.x.
#
# Read for build instructions:
# - https://github.com/tmux/tmux
# - https://gist.github.com/rothgar/cecfbd74597cc35a6018#gistcomment-1801422
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#
name="tmux"
version="2.3"
if [[ -n "$1" ]]; then
	version="$1"
fi
source_url="https://github.com/tmux/tmux/releases/download/${version}/tmux-${version}.tar.gz"
source_directory="${DPM_INSTALL_DIRECTORY}/${name}"

# Remove any existing version that yum may have installed.
echo -e "${RESET}${BBLUE}Removing any existing version of ${name}${RESET}"
yum -y remove tmux

if ! command_exists tmux ; then
    echo -e "${RESET}${BBLUE}Downloading, compiling, and installing ${name} ${GREEN}${version}${RESET}"
    cd "${DPM_INSTALL_DIRECTORY}" \
    && wget https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz \
    && tar -xf libevent-2.1.8-stable.tar.gz \
    && cd libevent-2.1.8-stable \
    && ./configure --prefix=/usr/local \
    && make \
    && sudo make install \
    && cd "${DPM_INSTALL_DIRECTORY}" \
    && wget "${source_url}" \
    && tar -xf "tmux-${version}.tar.gz" \
    && cd "tmux-${version}" \
    && LDFLAGS="-L/usr/local/lib -Wl,-rpath=/usr/local/lib" ./configure --prefix=/usr/local \
    && make \
    && sudo make install \
    && echo -e "${GREEN}${name} installed.${RESET}"
fi
