#!/usr/bin/env bash
source "${HOME}/.dotfiles/.dotfiles_includes"

##
# Clone, compile, and install WeeChat.
#
# Note that all of WeeChat's dependencies have been declared in ../yum, along
# with a variety of other utilities that should be installed. This script,
# therefore, assumes that WeeChat's dependencies are already installed.
#
# This was created and works on CentOS 6.x. It has also been tested on MacOS.
#
# Read for build instructions:
# https://weechat.org/files/doc/stable/weechat_user.en.html#source_package
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#

directory_dotfiles_packages="${HOME}/.dotfiles-packages"
weechat_directory="${directory_dotfiles_packages}/weechat"

weechat_version="v1.7"
if [[ -n "$1" ]]; then
	weechat_version="$1"
fi

echo -e "${BBLUE}Cloning, compiling, and installing WeeChat ${GREEN}${weechat_version}${RESET}"

if [[ ! -d "${directory_dotfiles_packages}" ]]; then
	mkdir -pv "${directory_dotfiles_packages}"
fi

rm -rf "${weechat_directory}" \
&& git clone git@github.com:weechat/weechat.git "${weechat_directory}"
cd "${weechat_directory}" \
&& git checkout "${weechat_version}" \
&& mkdir build \
&& cd build \
&& cmake .. \
&& make \
&& sudo make install \
&& echo -e "${GREEN}Weechat installed.${RESET}"
