#!/usr/bin/env bash
source "${DOTFILES_BOOTSTRAP_FILE}"

##
# Install PHP Composer.
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#

if command_exists php \
    && ! command_exists composer \
; then
    echo -e "${RESET}${BBLUE}Installing PHP Composer.${RESET}"
    curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin
fi
