#!/usr/bin/env bash
source "${DOTFILES_BOOTSTRAP_FILE}"

##
# Clone, compile, and install WeeChat.
#
# Note that all of WeeChat's dependencies have been declared in ../yum, along
# with a variety of other utilities that should be installed. This script,
# therefore, assumes that WeeChat's dependencies are already installed.
#
# This was created and works on CentOS 6.x. It has also been tested on MacOS.
#
# Read for build instructions:
# https://weechat.org/files/doc/stable/weechat_user.en.html#source_package
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#
name="weechat"
version="v1.7"
if [[ -n "$1" ]]; then
	version="$1"
fi
source_url="https://github.com/weechat/weechat.git"
source_directory="${DPM_INSTALL_DIRECTORY}/${name}"

echo -e "${RESET}${BBLUE}Removing any existing version of ${name}${RESET}"
yum -y remove weechat

echo -e "${RESET}${BBLUE}Cloning, compiling, and installing ${name} ${GREEN}${version}${RESET}"
rm -rf "${source_directory}" \
&& git clone "${source_url}" "${source_directory}"
cd "${source_directory}" \
&& git checkout "${version}" \
&& mkdir build \
&& cd build \
&& cmake .. \
&& make \
&& sudo make install \
&& echo -e "${GREEN}${name} installed.${RESET}"
