#!/usr/bin/env bash
source "${DOTFILES_INCLUDES_PATH}"

##
# Ensure correct, non-MacOS version of rsync is installed.
#
# MacOS carries a very old version, so replace it with the one defined in brew.
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#

brew install rsync
