#!/usr/bin/env bash
source "${HOME}/.dotfiles/.dotfiles_includes"

##
# Download, compile, and install latest version of symlinks.
#
# Info:
# - https://github.com/brandt/symlinks
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#
name="symlinks"
version="v1.4.3"
if [[ -n "$1" ]]; then
	version="$1"
fi
source_url="git@github.com:brandt/symlinks.git"
source_directory="${DPM_INSTALL_DIRECTORY}/${name}"

echo -e "${BBLUE}Downloading, compiling, and installing ${name} ${GREEN}${version}${RESET}"
cd "${DPM_INSTALL_DIRECTORY}" \
&& rm -rf "${source_directory}" \
&& git clone "${source_url}" "${source_directory}"
cd "${source_directory}" \
&& git checkout "${version}" \
&& make \
&& ln -vsfn "${source_directory}/symlinks" "${HOME}/bin/" \
&& echo -e "${GREEN}${name} installed.${RESET}"
