#!/usr/bin/env bash
source "${DOTFILES_BOOTSTRAP_FILE}"

##
# Install Percona's MySQL version and extensions.
#
# This only installs the server. To install all the tools, like `mysqldump`,
# run the `mysqltools_install` script.
#
# Notes:
# - If you get PID/sock issues, ensure permissions are set.
# - If mysqld won't start, check the standard mysql log files, and check
# /var/log/messages log for mysql issues, like running out of memory (ensure
# the box has enough), or SELinux not permitting actions (like preventing
# access to ~/.my.cnf).
#
# @author Dane MacMillan <work@danemacmillan.com>
# @link https://github.com/danemacmillan/dotfiles
# @license MIT
#
name="mysql"
version=""
if [[ -n "$1" ]]; then
	version="$1"
fi
source_url=""
source_directory=""

if ! command_exists ${name}; then
	echo -e "${RESET}${BBLUE}Installing ${name} server ${GREEN}${version}${RESET}"

	yum -y install \
	http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm \
	Percona-Server-server-56

	mkdir -pv /var/lib/mysql && chown -R mysql:mysql /var/lib/mysql && chmod -R 755 /var/lib/mysql
	mkdir -pv /var/log/mysql && chown -R mysql:mysql /var/log/mysql && chmod -R 755 /var/log/mysql
	mkdir -pv /home/mysql && chown -R mysql:mysql /home/mysql && chmod -R 770 /home/mysql
	/etc/init.d/mysql restart
	mysql_install_db
	/etc/init.d/mysql restart
	mysql_secure_installation
	/etc/init.d/mysql restart
	chkconfig mysql on

	echo -e "${GREEN}${name} server installed.${RESET}"
fi
