#!/usr/bin/env bash
source "${DOTFILES_BOOTSTRAP_FILE}"

if ! command_exists composer; then
  brew install composer
fi

if ! pecl list |grep -q xdebug ; then
  pecl install xdebug
fi

if [[ ! -f /usr/local/opt/php@7.1/lib/php/20160303/ioncubeloader.so ]]; then
	mkdir -p /usr/local/opt/php@7.1/lib/php/20160303
	cd $HOME/tmp
	wget https://downloads.ioncube.com/loader_downloads/ioncube_loaders_dar_x86-64.zip
	unzip ioncube_loaders_dar_x86-64.zip
	mv ioncube/ioncube_loader_dar_7.1.so /usr/local/opt/php@7.1/lib/php/20160303/ioncubeloader.so
fi
