#!/bin/sh

# Notes:
# https://forum.holochain.org/t/uninstall-nix/5133
# https://github.com/NixOS/nix/issues/1551
#


set -x

if [ -f /Library/LaunchDaemons/org.nixos.nix-daemon.plist ]; then
    sudo launchctl unload /Library/LaunchDaemons/org.nixos.nix-daemon.plist
    sudo rm /Library/LaunchDaemons/org.nixos.nix-daemon.plist
fi

if [ -f /etc/profile.backup-before-nix ]; then
    sudo mv /etc/profile.backup-before-nix /etc/profile
fi

if [ -f /etc/bashrc.backup-before-nix ]; then
    sudo mv /etc/bashrc.backup-before-nix /etc/bashrc
fi

if [ -f /etc/bash.bashrc.backup-before-nix ]; then
    sudo mv /etc/bash.bashrc.backup-before-nix /etc/bashrc
fi

if [ -f /etc/zshrc.backup-before-nix ]; then
    sudo mv /etc/zshrc.backup-before-nix /etc/zshrc
fi

sudo rm -rf /etc/nix
sudo rm -rf /nix

rm -rf ~/.nix-defexpr
unlink ~/.nix-profile

for i in $(seq 1 $(sysctl -n hw.ncpu)); do
    sudo /usr/bin/dscl . -delete "/Users/_nixbld$i"
done
sudo /usr/bin/dscl . -delete "/Groups/nixbld"

# Clean up remaining
sudo /usr/bin/dscl . -list /Users

sudo vifs
# and remove entry in /etc/synthetic.conf?
# Then delete apfs volume in disk utility.



